# =============================================================================
# VLLM Qwen2.5-Omni Video Captioning Configuration
# =============================================================================

[model]
name = "Qwen/Qwen2.5-Omni-7B-AWQ"
model_path = "./models/Qwen2.5-Omni-7B-AWQ"
trust_remote_code = true
dtype = "auto"
max_model_len = 24576

[hardware]
gpu_memory_utilization = 0.9
tensor_parallel_size = 1

[generation]
temperature = 0.7
max_tokens = 512
top_p = 0.9

[paths]
input_dir = "./videos"
output_dir = "./captions"

output_formats = ["txt", "csv", "json"]
# output_format = "csv"  - save in one format only
video_extensions = [".mp4", ".avi", ".mov", ".mkv", ".webm"]

[processing]
batch_size = 1
use_audio_in_video = false
overwrite_existing = true # overwrite caption files if already exist

[prompts]
trigger_word = "Nfj1nx"  # Optional
system_prompt = "You are a helpful assistant that describes videos in detail."
#user_prompt = "Please describe this video in detail, including what you see and hear."
user_prompt = '''1. **Main Content:**
    * What is the primary focus of the scene?
    * Who are the main characters visible?

2. **Object and Character Details:**
    * Don't refer to characters as 'individual', 'characters' and 'persons', instead always use their gender or refer to them with their gender.
    * Describe the appearance in detail
    * What notable objects are present?

3. **Actions and Movement:**
    * Describe ALL movements, no matter how subtle.
    * Specify the exact type of movement (walking, running, etc.).
    * Note the direction and speed of movements.

4. **Background Elements:**
    * Describe the setting and environment.
    * Note any environmental changes.

5. **Visual Style:**
    * Describe the lighting and color palette.
    * Note any special effects or visual treatments.
    * What is the overall style of the video? (e.g., realistic, animated, artistic, documentary)

6. **Camera Work:**
    * Describe EVERY camera angle change.
    * Note the distance from subjects (close-up, medium, wide shot).
    * Describe any camera movements (pan, tilt, zoom).

7. **Scene Transitions:**
    * How does each shot transition to the next?
    * Note any changes in perspective or viewing angle.

Please be extremely specific and detailed in your description. If you notice any movement or changes, describe them explicitly.
'''
