# =============================================================================
# VLLM Qwen2.5-Omni Prompts Configuration
# =============================================================================

[general]
trigger_word = "MyTr1gg3r"  # Optional trigger word for captions

# =============================================================================
# VIDEO PROMPTS
# =============================================================================
[video]
[video.round1]
mode = "multimodal"  # "multimodal" | "text"
system_prompt = "You are a highly attentive assistant that describes videos with extreme frame-by-frame precision."
user_prompt = '''
Describe the video in extreme detail, with these guidelines:

1. **Main Content:**
    * What is the primary focus of the scene?
    * Who are the main characters visible?

2. **Object and Character Details:**
    * Don't refer to characters as 'individual', 'characters' and 'persons', instead always use their gender or refer to them with their gender.
    * Describe the appearance in detail
    * What notable objects are present?

3. **Actions and Movement:**
    * Describe ALL movements, no matter how subtle.
    * Specify the exact type of movement (walking, running, etc.).
    * Note the direction and speed of movements.

4. **Background Elements:**
    * Describe the setting and environment.
    * Note any environmental changes.

5. **Visual Style:**
    * Describe the lighting and color palette.
    * Note any special effects or visual treatments.
    * What is the overall style of the video? (e.g., realistic, animated, artistic, documentary)

6. **Camera Work:**
    * Describe EVERY camera angle change.
    * Note the distance from subjects (close-up, medium, wide shot).
    * Describe any camera movements (pan, tilt, zoom).

7. **Scene Transitions:**
    * How does each shot transition to the next?
    * Note any changes in perspective or viewing angle.

Please be extremely specific and detailed in your description. If you notice any movement or changes, describe them explicitly.
'''

[video.round2]
mode = "text"  # "multimodal" | "text"
system_prompt = "You are an expert video caption refiner. Your task is to improve video captions based on specific instructions."
user_prompt = '''
    **Summarize the generated caption in 500 tokens, but with the following modifications:**
        * Write continuously, don't use multiple paragraphs, make the text form one coherent whole
        * Call the main character: {trigger_word}
        * Do not mention your task
        * Don't use references to video such as "the video begins" or "the video features" etc., but keep those sentences meaningful
        * Mention the clothing details of the characters
        * Use only declarative sentences
        * Don't mention the style of the video
        * Don't mention the name of the characters
'''

# =============================================================================
# IMAGE PROMPTS
# =============================================================================
[image]
[image.round1]
mode = "multimodal"  # "multimodal" | "text"
system_prompt = "You are an expert art and photography analyst with deep knowledge of visual composition, artistic techniques, and cultural contexts."
user_prompt = '''Analyze this image with comprehensive detail:

1. **Subject and Content:**
    * What is the main subject or focal point of the image?
    * Who or what is depicted? (Be specific about people, objects, scenes)
    * What is happening in the image? Describe any action or narrative.

2. **Artistic Style and Technique:**
    * What artistic style or movement does this represent? (e.g., Renaissance, Impressionism, Modern, Contemporary)
    * What medium appears to be used? (oil painting, watercolor, photography, digital art, etc.)
    * Describe the brushwork, texture, or photographic technique visible.

3. **Composition and Visual Elements:**
    * How is the composition arranged? (rule of thirds, symmetry, leading lines)
    * What is the perspective and viewpoint?
    * Describe the use of space, balance, and visual hierarchy.

4. **Color and Lighting:**
    * What is the color palette? (warm/cool, monochromatic, complementary)
    * How is light used? (natural/artificial, soft/harsh, directional)
    * What mood does the lighting create?

5. **Details and Symbolism:**
    * What specific details stand out? (clothing, objects, facial expressions)
    * Are there symbolic elements or cultural references?
    * What emotions or themes are conveyed?

6. **Technical Quality:**
    * What is the level of detail and craftsmanship?
    * How is depth and dimension achieved?
    * Comment on the overall execution and skill level.

Be thorough and precise in your analysis, treating this as a professional art critique or detailed photographic analysis.
'''

[image.round2]
mode = "text"  # "multimodal" | "text"
system_prompt = "You are an expert caption writer specializing in art and photography descriptions."
user_prompt = '''
    **Summarize the generated caption in 500 tokens, but with the following modifications:**
        * Write continuously, don't use multiple paragraphs, make the text form one coherent whole
        * Call the main character: {trigger_word}
        * Do not mention your task
        * Mention the clothing details of the characters
        * Use only declarative sentences
        * Don't mention the style of the image
        * Don't mention the name of the characters
'''