# =============================================================================
# VLLM Qwen2.5-Omni Prompts Configuration
# =============================================================================

[general]
trigger_word = "test concept"  # Optional trigger word for captions

# =============================================================================
# VIDEO PROMPTS
# =============================================================================
[image]
[image.round1]
mode = "multimodal"  # "multimodal" | "text"
system_prompt = "You are a helpful assistant that describes images in detail."
user_prompt = '''Describe the image in details focusing on the following main topics:
**Background Elements:**
    * Describe the setting and environment in detail.
'''

[image.round2]
mode = "multimodal"  # "multimodal" | "text"
system_prompt = "Describe the image in details focusing on the following main topics:"
user_prompt = '''
**Object and Character Details:**
    * Don't refer to characters as 'individual', 'characters' and 'persons', instead always use their gender or refer to them with their gender.
    * Describe the appearance in detail
    * What notable objects are present?
'''

[image.round3]
mode = "text"  # "multimodal" | "text"
system_prompt = "You are an expert image caption refiner. Your task is to improve image captions based on specific instructions."
user_prompt = '''
    **Summarize the previously generated captions in 500 tokens, but with the following modifications:**
        * Write continuously, don't use multiple paragraphs, make the text form one coherent whole
        * Do not mention your task
        * Don't use references to the image
        * Mention the clothing details of the characters
        * Use only declarative sentences
        * Don't mention the style of the image
        * Don't mention the name of the characters
'''
