# =============================================================================
# VLLM Qwen2.5-Omni Prompts Configuration
# =============================================================================

[general]
trigger_word = "test concept"  # Optional trigger word for captions

# =============================================================================
# VIDEO PROMPTS
# =============================================================================
[video]
[video.round1]
mode = "multimodal"  # "multimodal" | "text"
system_prompt = "You are a helpful assistant that describes videos in detail."
user_prompt = '''Describe the video in details focusing on the following main topics:
**Camera Work:**
    * Describe EVERY camera angle change.
    * Note the distance from subjects (close-up, medium, wide shot).
    * Describe any camera movements (pan, tilt, zoom).
'''

[video.round2]
mode = "multimodal"  # "multimodal" | "text"
system_prompt = "Describe the video in details focusing on the following main topics:"
user_prompt = '''
 **Object and Character Details:**
    * Don't refer to characters as 'individual', 'characters' and 'persons', instead always use their gender or refer to them with their gender.
    * Describe the appearance in detail
    * What notable objects are present?
'''

[video.round3]
mode = "text"  # "multimodal" | "text"
system_prompt = "You are an expert video caption refiner. Your task is to improve video captions based on specific instructions."
user_prompt = '''
    **Summarize the previously generated captions in 500 tokens, but with the following modifications:**
        * Write continuously, don't use multiple paragraphs, make the text form one coherent whole
        * Do not mention your task
        * Don't use references to video such as "the video begins" or "the video features" etc., but keep those sentences meaningful
        * Mention the clothing details of the characters
        * Use only declarative sentences
        * Don't mention the style of the video
        * Don't mention the name of the characters
'''
